Prueba2023/Models/ErrorViewModel.cs
namespace Prueba2023.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Prueba2023/Models/Persona.cs
namespace Prueba2023.Models
{
    public class Persona
    {
        public int Id { get; set; }
        public string? Identificacion { get; set; }
        public string? Nombres { get; set; }
        public string? Apellidos { get; set; }
        public string? TipoIdentificacion { get; set; }
        public string? Correo { get; set; }
    }
}

Prueba2023/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Prueba2023.Models;

namespace Prueba2023.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Prueba2023/Controllers/PersonaController.cs
using Microsoft.AspNetCore.Mvc;
using Prueba2023.Data;
using Prueba2023.Models;

namespace Prueba2023.Controllers
{
    public class PersonaController : Controller
    {
        private readonly IPersona _ipersona;

        public PersonaController(IPersona ipersona)
        {
            _ipersona = ipersona;
        }

        public IActionResult Index()
        {
            var persona = _ipersona.ObtenerPersonas();
            return View(persona);
        }

        public IActionResult Detalle(int id)
        {
            var persona = _ipersona.ObtenerPersonaPorId(id);
            return View(persona);
        }

        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CrearTest(Persona persona)
        {
            _ipersona.InsertarPersona(persona);
            return RedirectToAction("Index");
        }

        public IActionResult Editar(int id)
        {
            var persona = _ipersona.ObtenerPersonaPorId(id);
            return View(persona);
        }

        [HttpPost]
        public IActionResult Editar(Persona persona)
        {
            _ipersona.ActualizarPersona(persona);
            return RedirectToAction("Index");
        }

        public IActionResult Eliminar(int id)
        {
            var persona = _ipersona.ObtenerPersonaPorId(id);

            if (persona == null)
                return NotFound();

            return View(persona);
        }

        [HttpPost]
        public IActionResult EliminarConfirmado(int id)
        {
            _ipersona.EliminarPersona(id);
            return RedirectToAction("Index");
        }

    }
}

Prueba2023/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Prueba2023/Views/Persona/Crear.cshtml
@model Persona

<h1>Crear nueva persona</h1>
<form asp-action="Crear" method="post">
    <div class="form-group">
        <label asp-for="Identificacion" class="control-label"></label>
        <input asp-for="Identificacion" class="form-control" />
        <span asp-validation-for="Identificacion" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Nombres" class="control-label"></label>
        <input asp-for="Nombres" class="form-control" />
        <span asp-validation-for="Nombres" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Apellidos" class="control-label"></label>
        <input asp-for="Apellidos" class="form-control" />
        <span asp-validation-for="Apellidos" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="TipoIdentificacion" class="control-label"></label>
        <input asp-for="TipoIdentificacion" class="form-control" />
        <span asp-validation-for="TipoIdentificacion" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Correo" class="control-label"></label>
        <input asp-for="Correo" class="form-control" />
        <span asp-validation-for="Correo" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Guardar</button>
        <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
    </div>
</form>

Prueba2023/Views/Persona/Detalle.cshtml
@using Prueba2023.Models
@model Persona

<h1>Detalle de la persona</h1>

<dl class="row">
    <dt class="col-sm-2">Identificacion</dt>
    <dt class="col-sm-10">@Model.Identificacion</dt>

    <dt class="col-sm-2">Nombres</dt>
    <dt class="col-sm-10">@Model.Nombres</dt>

    <dt class="col-sm-2">Apellidos</dt>
    <dt class="col-sm-10">@Model.Apellidos</dt>

    <dt class="col-sm-2">Tipo Identificacion</dt>
    <dt class="col-sm-10">@Model.TipoIdentificacion</dt>

    <dt class="col-sm-2">Correo</dt>
    <dt class="col-sm-10">@Model.Correo</dt>
</dl>
<p>
    <a asp-action="Index" class="btn btn-secondary">Regresar a la lista de personas</a>
</p>

Prueba2023/Views/Persona/Editar.cshtml
@using Prueba2023.Models
@model Persona

<h1>Editar persona</h1>
<form asp-action="Editar" method="post">
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label asp-for="Identificacion" class="control-label"></label>
        <input asp-for="Identificacion" class="form-control" />
        <span asp-validation-for="Identificacion" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Nombres" class="control-label"></label>
        <input asp-for="Nombres" class="form-control" />
        <span asp-validation-for="Nombres" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Apellidos" class="control-label"></label>
        <input asp-for="Apellidos" class="form-control" />
        <span asp-validation-for="Apellidos" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TipoIdentificacion" class="control-label"></label>
        <input asp-for="TipoIdentificacion" class="form-control" />
        <span asp-validation-for="TipoIdentificacion" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Correo" class="control-label"></label>
        <input asp-for="Correo" class="form-control" />
        <span asp-validation-for="Correo" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Guardar</button>
        <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
    </div>
</form>

Prueba2023/Views/Persona/Eliminar.cshtml
@using Prueba2023.Models
@model Persona

<h1>Eliminar persona</h1>
<h3>¿Estás seguro que deseas eliminar la siguiente persona?</h3>
<dl class="row">
    <dt class="col-sm-2">Identificación</dt>
    <dt class="col-sm-10">@Model.Identificacion</dt>

    <dt class="col-sm-2">Nombres</dt>
    <dt class="col-sm-10">@Model.Nombres</dt>

    <dt class="col-sm-2">Apellidos</dt>
    <dt class="col-sm-10">@Model.Apellidos</dt>

    <dt class="col-sm-2">Tipo de identificación</dt>
    <dt class="col-sm-10">@Model.TipoIdentificacion</dt>

    <dt class="col-sm-2">Correo electrónico</dt>
    <dt class="col-sm-10">@Model.Correo</dt>
</dl>
<form asp-action="EliminarConfirmado" method="post">
    <input asp-for="Id" type="hidden" />
    <div class="form-group">
        <button type="submit" class="btn btn-danger">Eliminar</button>
        <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
    </div>
</form>

Prueba2023/Views/Persona/Index.cshtml
@using System.Collections;
@using Prueba2023.Models
@model IEnumerable<Persona>

<h1>Personas</h1>
<p>
    <a asp-action="Crear">Crear nueva persona</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>Identificacion</th>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Tipo Identificacion</th>
            <th>Correo</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var persona in Model)
        {
            <tr>
                <td>@persona.Identificacion</td>
                <td>@persona.Nombres</td>
                <td>@persona.Apellidos</td>
                <td>@persona.TipoIdentificacion</td>
                <td>@persona.Correo</td>
                <td>
                    <a asp-action="Detalle" asp-route-id="@persona.Id">Detalle</a>
                    <a asp-action="Editar" asp-route-id="@persona.Id">Editar</a>
                    <a asp-action="Eliminar" asp-route-id="@persona.Id">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Prueba2023/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Prueba2023</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Prueba2023.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Prueba2023</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Persona" asp-action="Index">Persona</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Prueba2023 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>